### PR TITLE
Date component issue #1749

### PR DESCRIPTION
**Pull request by gabrielgrover**
# Description
In order to fix this issue we had to make changes to the following files

/src/utils/validations/date/date.js
    Added new functionality to DateValidator that takes in a minDate and
    maxDate in the constructor.  Throws an error if either is not ISO-format.

/src/utils/helpers/date/date.js
    Added new function to DateHelper that checks whether a given date is in
    a given date range.

/src/utils/decorators/input-validation/input-validation.js
    Added new private method to InputValidation that abstracts the type check
    of internalValidations in the Date Component.  See @andrewjtait's
    comment in issue #1749.

# TODO

- DateComponent needs unit tests

- [ input-validation.js was refactored in order to fix the issue where a user could manually enter a date that was out of range in a Date Component.] Release notes

# Related Issues / Pull Requests
Issue #1749 

# Testing Instructions
See initial post on issue #1749 for instructions on how to test.

### CODE REVIEW

**Comment by andrewjtait** [comment]
@Euklidian-Space Looks good! I will try and look into the failing specs as soon as possible 👍 Thanks again for the contribution!

**Comment by ianoxley** [comment]
@Euklidian-Space Thanks for this 👍 

If you can fix the code coverage issue with the tests we should be able to get this merged. According to the coverage report it's this line that doesn't have any coverage: https://github.com/Sage/carbon/blob/7f16cc18210e1c87e7a27f834f4148b91172f2b3/src/components/date/date.js#L133

**Comment by Euklidian-Space** [comment]
Hey @ianoxley.  I'll get on this during the upcoming weekend.  Been swamped lately.

**Comment by Euklidian-Space** [comment]
Hey @ianoxley.  This looks good to go!

**Comment by Euklidian-Space** [comment]
Hey @andrewjtait it has been sometime since my last contribution.  What file do I put the release notes in again?

Thanks,
Euklidian-Space

**Comment by ianoxley** [comment]
@Euklidian-Space I think it might've changed since your last contribution 😄

We've added some notes about release notes to the [README](https://github.com/Sage/carbon#adding-release-notes). Basically all you need to do is create a yml file in [`change_log/next`](https://github.com/Sage/carbon/tree/master/change_log/next) describing your change.

Let us know if you have any more questions.

**Comment by Euklidian-Space** [comment]
Hey @andrewjtait, I fixed the first issue you found.  It was merely an issue with not including the endpoints of the date range.  However for the second issue I need a little help.  I pinpointed it to the file src/utils/validations/date/date.js.  It is the DateValidator.  The message() method calls the function validationMessage in src/utils/helpers/validations/validations.js.  The second argument to that method is a string 'errors.messages.wrong_format'.  I assume we have to pass something like 'errors.messages.out_of_range'.  However, if I pass that I get an error.  Maybe something needs to be added to the i18n-js configuration?

**Comment by ianoxley** [comment]
@Euklidian-Space If you only get the error when running the demo site, you could try adding your `out_of_range` error to here:

https://github.com/Sage/carbon/blob/951c936f6462030a9f58cc97b6decd06d0bc04c6/demo/i18n/en.js#L102

**Comment by jamime** [comment]
Closing as we have a new date component in progress. Additionally, now that #2481 has been merged we would advise our consumers to use yup to validate the user input.

**Pull request closed without merging**
