### PR TITLE
docs(search): update stories with default values to not have same text used for placeholder FE-4069

### PR DESCRIPTION
**Pull request by edleeks87**
### Proposed behaviour

Updates the `defaultValue` text so it isn't the same text used for `placeholder` to make it clearer
that there is what using each prop does.

The `InputIconToggle` is slightly out of alignment within the `Search` component, when it is focused
you can see it is slightly misaligned. Adding a transform to move it down vertically by 1% solves
the issue as it is trying to centre itself within the input but the input has a height of 35px

### Current behaviour

Stories that use `defaultValue` all have text `Search` which is similar to the `placeholder` text.
The `InputIconToggle` is slightly out of alignment within the `Search` component, when it is focused
you can see it is slightly misaligned.

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

image

### Testing instructions

`design-system-search--default-story` etc

### CODE REVIEW

**Review by dawidzarzycki — APPROVED** [review]

**Review by mmaciorowski-sage — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by sjohnson-sage — COMMENTED** [review]
I don't think the icon is misaligned because it's positioned centre, it's the extra 2px bottom padding on the Search that's causing the issue

I think just removing that padding will solve it rather than adding the transform, or even adding a -2px bottom margin to the icon (I think this is a situation it's ok to use one)

**Comment by edleeks87** [comment]
Yeah initially I though it was that but removing the padding still leaves it overlapping more on the top than the bottom

image


> I don't think the icon is misaligned because it's positioned centre, it's the extra 2px bottom padding on the Search that's causing the issue
> 
> I think just removing that padding will solve it rather than adding the transform, or even adding a -2px bottom margin to the icon (I think this is a situation it's ok to use one)

**Comment by sjohnson-sage** [comment]
> Yeah initially I though it was that but removing the padding still leaves it overlapping more on the top than the bottom
> 
> image
> 
> > I don't think the icon is misaligned because it's positioned centre, it's the extra 2px bottom padding on the Search that's causing the issue
> > I think just removing that padding will solve it rather than adding the transform, or even adding a -2px bottom margin to the icon (I think this is a situation it's ok to use one)

Fair enough, I do think a negative bottom margin is a better solution for this but I'll let it go here as it's pretty minor

**Review by mmaciorowski-sage — APPROVED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]

**Pull request merged**
