### PR TITLE
docs: updated favicon

### PR DESCRIPTION
**Pull request by dcporter65**
### Proposed behaviour

- Display the Carbon logo as the favicon in the desktop browser tab [FE-5627](https://jira.sage.com/browse/FE-5627)
- Display the Carbon logo on the Home screen if the user selects **Add to Home screen** on a mobile device
- Changes the value of `brandTitle`. which appears when you mouse over the logo on the top left of the screen to "Carbon by Sage".
- Changes spelling of "Github" to "GitHub" on Welcome page
- Other minor capitalization and punctuation changes

### Current behaviour

- The current favicon is the default Storybook logo 
image

- `brandTitle` is currently "Sage DS by Carbon"

### Checklist

- [ ] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [x] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Run Carbon locally and check that the favicon displayed in the browser tab is Carbon, not Storybook.

image

Mouse over the Carbon logo in the top left of the screen to display the correct Alt text - "Carbon by Sage"

Use the network IP address and access the Carbon site from a mobile device. Select **Add to Home Screen** and check that the Carbon logo appears on the device's home screen.

### CODE REVIEW

**Review by AndrewLindsey — DISMISSED** [review]
With the caveat that I can't confirm whether the mobile aspect works. Ok on desktop in Edge, Firefox, Chrome.

**Comment by dcporter65** [comment]
> With the caveat that I can't confirm whether the mobile aspect works. Ok on desktop in Edge, Firefox, Chrome.

@AndrewLindsey When you run Storybook locally, npm provides an IP address that is accessible "on your network". Put this IP address into a browser on your phone or iPad to view the site. Then try to add the site to your Home screen.

**Comment by AndrewLindsey** [comment]
> > With the caveat that I can't confirm whether the mobile aspect works. Ok on desktop in Edge, Firefox, Chrome.
> 
> @AndrewLindsey When you run Storybook locally, npm provides an IP address that is accessible "on your network". Put this IP address and port into a browser on your phone or iPad to view the site. Then try to add the site to your Home screen.

Just hangs looking for the address on my iPhone and iPad.

**Review by edleeks87 — APPROVED** [review]
Changes look good to me @dcporter65, before this PR is merged can you rebase with master. You could also squash all the commits into a single one but it would also be fine to leave it all as separate ones

**Review by Parsium — DISMISSED** [review]

**Pull request closed without merging**
