### PR TITLE
fix(tabs-header): set cursor to default in adjacent blank areas (FE-4715)

### PR DESCRIPTION
**Pull request by mrtn-a**
### Proposed behaviour
This PR is to fix issue [4686](https://github.com/Sage/carbon/issues/4686). 
It removes the cursor:pointer from the adjacent non-interactive blank areas around `Tabs` on hover, setting cursor to default.

### Current behaviour
Currently when hovering on the adjacent space around the Tabs, the cursor keeps as cursor:pointer, also on the blank areas which are not interactive.

(https://carbon.sage.com/?path=/docs/tabs--default-story)

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by edleeks87 — COMMENTED** [review]
Hey @mrtn-a the code changes look good to me, could you update the commit message scope to be `fix(tabs-header):...` rather than `fix(tabs)...` please

**Comment by mrtn-a** [comment]
> Hey @mrtn-a the code changes look good to me, could you update the commit message scope to be `fix(tabs-header):...` rather than `fix(tabs)...` please

done, thank you!

**Review by edleeks87 — APPROVED** [review]

**Comment by edleeks87** [comment]
@mrtn-a thanks, I'll get a second reviewer on this and run the builds etc once they approve 🎉

**Review by samtjo — APPROVED** [review]

**Comment by mrtn-a** [comment]
@Sage/carbon-qa please let me know if you need anything from my side? would be great if we could move with this PR please! :)

**Review by DlgSHi — APPROVED** [review]

**Pull request merged**
