### PR TITLE
Add .vscode/settings.json

### PR DESCRIPTION
**Pull request by ianoxley**
Exclude the `.git`, `coverage`, `lib`, and `node_modules` from displaying in the project explorer.

### CODE REVIEW

**Comment by andrewjtait** [comment]
Don't know about anyone else but I prefer being able to see all this - can this not be optional per user?

**Comment by andrewjtait** [comment]
If it's hidden behind a `.gitignore` then you can have this locally and we don't need to force everyone else to have the same settings?

**Comment by andrewjtait** [comment]
You may even prefer to add these settings to `~/Library/Application Support/Code/User/settings.json` so they apply over all of your local projects.

**Comment by ianoxley** [comment]
@andrewjtait It reduces the noise when you open files via Cmd+P. Plus users can still override these in their user settings.

Plus it seems to be a common thing:

* https://github.com/facebook/jest/blob/master/.vscode/settings.json
* https://github.com/facebook/jest/blob/master/.vscode/settings.json

**Pull request merged**
