### PR TITLE
refactor(checkable-input): move to internal folder

### PR DESCRIPTION
**Pull request by sjohnson-sage**
### Proposed behaviour
Moved `CheckableInput` into `src/__internal__` folder as it's only for use within Carbon

### Current behaviour
`CheckableInput` is currently in `src/__experimental__` folder

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions
Storybook still builds and all tests still pass.

### CODE REVIEW

**Review by grabkowski — COMMENTED** [review]
shouldn't this component be in `src/components/__internal__` folder instead of `src/__internal__`?
It's  a component and it will be one level less in imports.

**Comment by sjohnson-sage** [comment]
> shouldn't this component be in `src/components/__internal__` folder instead of `src/__internal__`?
> It's a component and it will be one level less in imports.

We currently don't have a `src/components/__internal__` and already have some internal components in `src/__internal__` - we'd have to move all of them if that's the case

**Comment by grabkowski** [comment]
> > shouldn't this component be in `src/components/__internal__` folder instead of `src/__internal__`?
> > It's a component and it will be one level less in imports.
> 
> We currently don't have a `src/components/__internal__` and already have some internal components in `src/__internal__` - we'd have to move all of them if that's the case

we should have all components in the `components` folder IMO. I'll approve this and raise that issue later.

**Review by grabkowski — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by Alec-Walker-Sage — APPROVED** [review]

**Pull request merged**
