### PR TITLE
build: replace cpx with cpy-cli - FE-3344

### PR DESCRIPTION
**Pull request by dawidzarzycki**
### Proposed behaviour
Replacing our old `cpx` library which is no more maintained with new `cpy-cli`
It will fix as well our vulnerabilities warnings

### Current behaviour
For now we have cpx package to copy our files. The package has latest release 4 years ago and is no more maintained. 

### Checklist

- [ ] <del> Commits follow our style guide
- [ ] <del> Screenshots are included in the PR if useful
- [ ] <del> All themes are supported if required
- [ ] <del> Unit tests added or updated if required
- [ ] <del> Cypress automation tests added or updated if required
- [ ] <del> Storybook added or updated if required
- [ ] <del> Typescript `d.ts` file added or updated if required
- [ ] <del> Carbon implementation and Design System documentation are congruent

### CODE REVIEW

**Review by edleeks87 — DISMISSED** [review]

**Comment by edleeks87** [comment]
When you run the scripts it's copying over the tests as well which it doesn't do with `cpx`

**Review by jamime — COMMENTED** [review]
Let me know once this has been fixed @dawidzarzycki.

**Review by edleeks87 — APPROVED** [review]

**Review by jamime — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Comment by sianford** [comment]
Tested by running command `npm run copy-files` in both this branch and the `master` branch and comparing the files in the newly generated `lib` directory in both branches. Directory content matches. Testing passed

**Pull request merged**
