### PR TITLE
fix(form): fix sticky footer - FE-4491

### LINKED ISSUE #4538: Height of form with sticky footer is too big
### Current behaviour

The new footer behaviour makes the form a nested scrollable panel.  The height of the panel has not been calculated correctly when a heading is included before the form, so the outer window also requires scrolling in order to see the form footer.

image

### Expected behaviour

The panel containing the form should be sized so it is fully visible on the screen.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/modest-babbage-gr6f9?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

94.1.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4658: StickyFooter adds unneeded space and scrollbars
### Current behaviour

I don't know the height of the content of my form so I want to use StickyFooter to always see the footer.

PBs : 
- A lot of unneeded space is added if the content is small
- A double scrollBar appears if the content is too big

see sandbox here
https://codesandbox.io/s/busy-brook-i5fby?file=/src/index.js

### Expected behaviour

The dialog/form should adapt to the content and the footer should be sticky only when needed.

see sandbox :
https://codesandbox.io/s/elastic-violet-nl1sz?file=/src/index.js

### CodeSandbox or Storybook URL

https://codesandbox.io/s/busy-brook-i5fby?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

92.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

Fixes #4538
Fixes #4658

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### CODE REVIEW

**Review by samtjo — COMMENTED** [review]
This has broken the sticky footer inside of `DialogFullScreen` 

image

I'm not sure flex is the way to go here unless the form container has a specified height

**Comment by edleeks87** [comment]
@mkrds there's nothing else for me to add that Sam hasn't already 👍

**Review by edleeks87 — APPROVED** [review]

**Review by samtjo — APPROVED** [review]

**Comment by mkrds** [comment]
Fixes #4658

**Review by divyajindel — APPROVED** [review]

**Pull request merged**
