### PR TITLE
fix(loader): give loader the correct role and aria-label prop - FE-4635

### LINKED ISSUE #4644: Loader - Accessibility violation in the 'inside buttons' story
### Current behaviour

There is an accessibility violation against the `inside button` story stating "Ensures buttons have discernible text". Full violation details are:

Critical - Element does not have inner text that is visible to screen readers
Serious - aria-label attribute does not exist or is empty
Serious - aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Serious - Element has no title attribute
Minor - Element's default semantics were not overridden with role="none" or role="presentation"

Loader_insideButtons_accessibilty_violation

### Expected behaviour

There are no accessibility violations.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/loader--inside-buttons

### JIRA Ticket (Sage Only)

FE-4635

### Suggested Solution

Add the relevant aria-label or aria-labelledby attributes to resolve the issue.

### Carbon Version

102.4.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
When a Loader component is nested in a button, axe throws an error to say that there is no
discernible text. Loader should have a role of progressbar and an aria-label to solve this issue.

fixes #4644

### Proposed behaviour

- Loader should have a role of `progressbar`
- aria-label prop has been made available for Loader to use
- When a Loader is nested inside of a Button component there are now no logged accessibility issues
Screenshot 2021-12-22 at 15 39 00

### Current behaviour

- Loader has no role
- aria-label is not available for Loader to use 
- When a Loader is nested inside of a Button component there is an accessibility issued logged by axe
Screenshot 2021-12-22 at 15 39 40

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

Visit `Loader -> inside buttons` example in storybook. There should not be accessibility errors on this example.

### CODE REVIEW

**Review by samtjo — COMMENTED** [review]
Code looks good to me, you just need to change the commit message so the fixes bit references the Github issue, not the Jira ticket. This will link this PR to the Github issue and close it when it's merged

**Comment by DipperTheDan** [comment]
> Code looks good to me, you just need to change the commit message so the fixes bit references the Github issue, not the Jira ticket. This will link this PR to the Github issue and close it when it's merged

Good spot @samtjo . I think I was in full Christmas mode at this point so completely missed the Github issue 😢
I'll get the commit amended 👍🏻

**Review by samtjo — DISMISSED** [review]

**Review by grabkowski — DISMISSED** [review]

**Comment by harpalsingh** [comment]
Checked voiceover and code for the correct props.

**Review by DlgSHi — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by grabkowski — APPROVED** [review]

**Pull request merged**
