### PR TITLE
Fix invalid HTML when using CSSTransitionGroup

### PR DESCRIPTION
**Pull request by ianoxley**
Pass the `component='div'` prop to all instances of `CSSTransitionGroup` that contain block-level content.

By default `CSSTransitionGroup` uses a `<span>` tag, which can lead to invalid HTML such as:

```html
<span>
  <div>
    My component
  </div>
</span>
```

By setting the `component` prop to the string `div` we ensure that the component HTML is valid HTML and doesn't include incorrectly nested tags.

### CODE REVIEW

**Comment by SeanArmstrong** [comment]
Do we think this could be a breaking change due to the CSS differences? QA would probably pick up on this if it is the case

**Comment by ianoxley** [comment]
@SeanArmstrong It _shouldn't_ be, as all that has changed is the tag used in the selector.

**Comment by andrewjtait** [comment]
devs shouldn't be hanging off element types really so wouldn't worry about it being a breaking change

**Comment by ianrobsonsage** [comment]
loaded the branch 'fix-csstransition-html' of carbon, compared the following components with carbon.sage.com. No differences found. QA Passed.

- AnimatedMenuButton
- Carousel
- Flash
- ShowEditPod
- Table
- Toast

**Pull request merged**
