### PR TITLE
Dropdown component linting fixes

### PR DESCRIPTION
**Pull request by paulsturgess**
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `dropdown` components to pre-emptively resolve the errors.

- [x] Dropdown
- [x] DropdownFilter
- [x] DropdownFilterAjax

There are no functional changes to the components.

#### Notes
The Dropdown component was not specifically handling key presses other than `up`, `down` and `return`. The linter wanted a default case added to the case statement, so I've set it to set highlighted as null (previously it was setting it to undefined). This should not change the behaviour but I did need to add a spec to keep the coverage at 100%.

### CODE REVIEW

**Comment by paulsturgess** [comment]
The linting issues are resolved in this PR except one relating to `no-param-reassign`.
It means you can't do:
```
(foo) => {
   let foo = 'bar'
}
```
Which seems a good rule. However, you also can't do:
```
(foo) => {
   foo.bar = 'bar'
}
```
Which seems quite strict. This is a configurable option though, so the rule can be setup to raise
an error on the first example, but not the second. http://eslint.org/docs/rules/no-param-reassign

The code that's raising this is the Dropdown component where it adjusts the `scrollTop` property on
the list:
https://github.com/Sage/carbon/blob/ea26aa34c1945179615266f5bd1f6cf2263b9d0c/src/components/dropdown/dropdown.js#L447

There's also another one in the DropdownFilter component:
https://github.com/Sage/carbon/blob/ea26aa34c1945179615266f5bd1f6cf2263b9d0c/src/components/dropdown-filter/dropdown-filter.js#L268

**Comment by abramin** [comment]
@paulsturgess We could change the rule to `props: false` to allow property modification. Will make that change in Carbon-Factory. We could pause this PR until that update if that sounds good?

**Comment by SeanArmstrong** [comment]
This change has been made in the latest patch of carbon-factory - https://github.com/Sage/carbon-factory/releases/tag/v1.1.6

**Comment by paulsturgess** [comment]
I've just pulled down carbon-factory 1.1.6 and can confirm the linting errors regarding `no-param-reassign` are no longer showing up 👍

**Comment by ianoxley** [comment]
Are we sure change the linting rules for this is a good idea?

> React is pretty flexible but it has a single strict rule:
> 
> **All React components must act like pure functions with respect to their props.**

You _could_ argue the `Dropdown` isn't modifying its props, but `DropdownFilter` appears to be.

**Comment by abramin** [comment]
@ianoxley You're right - we shouldn't be modifying props. I wonder though if we leave this rule as it allows reassignment of object properties in general (i.e. for objects that aren't `props`). Or do we want to enforce a strict functionalist paradigm and never allow it.

**Comment by sianford** [comment]
Tested in Safari, Chrome and Firefox browsers. The 'disabled' and 'readOnly' props should be Booleans but appear to be text boxes in the DropdownFilter and DropdownFilterAjax components.

**Pull request merged**
