### PR TITLE
[CARBON-948] Add the Portal component and apply to the Tooltip decorator

### PR DESCRIPTION
**Pull request by paulsturgess**
# Description
The Portal component pulls a component out into the top level of the DOM. The benefit of this is so that it is not effected by it’s position in the markup and cascading styles.

I have set the z-index of the tooltip to 1 + `z-dialog` to ensure it appears above modals.

The underlying functionality is provided by the library: https://github.com/tajo/react-portal

# TODO
- [x] Release notes
- [x] Specs for the new `<Portal>` component

# Related Issues / Pull Requests
CARBON-948

# Testing Instructions
Test that the Help and Icon tooltips remain positioned in the same way when tweaking the props for the position of the tooltip.

### CODE REVIEW

**Comment by ianrobsonsage** [comment]
QA Passed.

Tested the Tooltip, Help and Icon components across all browsers. Performance identical to current Carbon Demo site performance.

Will raise a separate ticket to make it not possible to select unworkable combinations of TooltipPosition and TooltipAllign

**Comment by andrewjtait** [comment]
We should test this in GAC as well - going to reopen for QA.

**Comment by SeanArmstrong** [comment]
help


There is a issue where the portal is overlapping the icon or something similar. Not sure how much of a problem this is

**Comment by andrewjtait** [comment]
@SeanArmstrong I think this will probably need fixing

**Comment by ianrobsonsage** [comment]
Qa Passed

In Carbon tested the Tooltip, Help and Icon components across all browsers. Performance identical to current Carbon Demo site performance. Previous issue of responsiveness of Tooltip now fixed.

In GAC tested the Tooltip in both the Contacts and Products and Services areas. No issues found.

**Comment by SeanArmstrong** [comment]
Had a look at IE, Safari and Firefox. All looks good

**Pull request merged**
