### PR TITLE
refactor: Add internal `usePrevious` hook (FE-4914)

### PR DESCRIPTION
**Pull request by Parsium**
### Proposed behaviour

- Introduce new `usePrevious` hook - which implements the same function used separately within components `DateRange`, `Drawer` and `Decimal`.
- Remove the replicated code within the three components.
- Refactor `Decimal`'s verification code that provides warning if component has been changed from controlled to uncontrolled (or vice visa).

### Current behaviour

A `usePrevious` function is defined in these three separate components.  

### Checklist

- [x] Commits follow our style guide
~~- [ ] Related issues linked in commit messages if required~~
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
~~- [ ] Cypress automation tests added or updated if required~~
~~- [ ] Storybook added or updated if required~~
~~- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required~~
~~- [ ] Typescript `d.ts` file added or updated if required~~

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

Since Babel has been configured with `@babel/preset-typescript` - and Jest, Storybook and Cypress have been configured to use our Babel config - the Typescript hook can be imported into regular Javascript files.  
https://babeljs.io/docs/en/babel-plugin-transform-typescript

### Testing instructions

Double check for any inconsistent behaviour in `Drawer`, `DateRange` and `Decimal`.

### CODE REVIEW

**Review by samtjo — APPROVED** [review]
Looks good, and nice use of TypeScript Generics 👌🏻

**Comment by samtjo** [comment]
Actually @Parsium I think this should be a `refactor` commit rather than a `feat` - we're essentially just refactoring our internal code, and providing nothing new to the users so there's no need to generate a minor release for this

**Review by samtjo — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by DipperTheDan — COMMENTED** [review]
Good job with doing it in TS 👏🏻 
You've done a better than I would have; I would have done it JS 🥲

**Pull request merged**
