### PR TITLE
feat(icon): add icons

### PR DESCRIPTION
**Pull request by harpalsingh**
### Proposed behaviour
5 new icons have been added to the icon font, they are:

- calender_today
- lookup
- pause_circle
- play_circle
- scan

### Checklist

- [x] Release notes (Conventional Commits) 
- [ ] Unit tests
- [x] Cypress automation tests
- [ ] Storybook added or updated
- [ ] Theme support
- [x] Typescript `d.ts` file added or updated

### Testing instructions
Run storybook and view the listed new icons at the top from the options in knobs.

#### Visuals
Screenshot 2020-01-31 at 14 22 53
Screenshot 2020-01-31 at 14 22 45
Screenshot 2020-01-31 at 14 22 38
Screenshot 2020-01-31 at 14 22 29
Screenshot 2020-01-31 at 14 22 20

### CODE REVIEW

**Comment by blaky** [comment]
Hi @chrisbarber86 and @jamime ,

We would like to get access to these icons in Carbon as soon as possible as we have a very tight deadline to meet and the UX team counts on these icons included to our delivery.

Thank you

**Comment by harpalsingh** [comment]
@jamime Comments were addressed can you re-review pls?

**Comment by jamime** [comment]
@blaky releasing now :)

**Pull request merged**
