### PR TITLE
CARBON-887 move error state to form-summary from save-button

### PR DESCRIPTION
**Pull request by abramin**
# Description

**BEFORE**:

screen shot 2017-06-30 at 15 07 36

**AFTER**

screen shot 2017-07-03 at 14 57 00

Puts grey background around summary rather than just save button.

* Also fixes some linter warnings by re-ordering methods. lowers errors to 46.

### CODE REVIEW

**Comment by toni-leigh** [comment]
The padding in the graphics seems really large?

**Comment by abramin** [comment]
It may be the padding added by this class `carbon-form-save` - was on the button. Will investigate

**Comment by toni-leigh** [comment]
It looks possibly like a duplicated class, it should be `8px` I think according to the designs

**Comment by andrewjtait** [comment]
screen shot 2017-07-03 at 10 42 58

^ for reference, it should look like this

**Comment by abramin** [comment]
Have updated after image @andrewjtait @toni-leigh

**Pull request merged**
