### PR TITLE
chore(deps): upgrade jest

### PR DESCRIPTION
**Pull request by sjohnson-sage**
### Proposed behaviour
Upgrade `jest` to fix a dependabot alert for `node-notifier`

### Current behaviour
`node-notifier` version is below `8.0.1` and therefore has a security issue

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### CODE REVIEW

**Review by ianforster-sage — APPROVED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Review by jamime — COMMENTED** [review]
We've had issues in the past when we had different versions of `babel-jest` and `jest`. Can we update them both, and `@types/jest`, if theres a matching version available.

**Update**: Maybe it was `jest`/`jest-cli` https://github.com/Sage/carbon/pull/2909 that I was thinking of.

**Comment by sjohnson-sage** [comment]
> We've had issues in the past when we had different versions of `babel-jest` and `jest`. Can we update them both, and `@types/jest`, if theres a matching version available.

Yeah sure, just out of interest what issues have we had with that?

**Review by edleeks87 — APPROVED** [review]

**Review by jamime — APPROVED** [review]

**Comment by jamime** [comment]
> > We've had issues in the past when we had different versions of `babel-jest` and `jest`. Can we update them both, and `@types/jest`, if theres a matching version available.
> 
> Yeah sure, just out of interest what issues have we had with that?

When we were using `npm install` the tests would fail.
But when we were running `npm ci` the tests would pass.

After a lot of debugging, IIRC the child process was using the `jest` defined in the package json but the parent process was using the `jest` bundled with `jest-cli` or vice-versa. I think this was largely because we were using both `jest` and `jest-cli`.

I'd like to keep `babel-jest` and `jest` with the same version, they're developed in the same monorepo and are released at the same time.

`@types/babel` is developed in a different repo, but we should ensure we use a version that corresponds to our version of `jest`.

**Review by ianforster-sage — APPROVED** [review]

**Pull request merged**
