### PR TITLE
Icon font updates - 20px size / New brand style / 2 new icons

### PR DESCRIPTION
**Pull request by harpalsingh**
### Proposed behaviour

- Icon font small size changed to minimum 20px
- 2 new icons added
- Icon font updated to new brand style

The 2 new icons added:

- check_all
- check_none

Screenshot 2023-05-23 at 10 54 12

**Visuals of Icons inside Carbon:**

### A few examples of before/after

A few examples of new style update and font size change for the smallest possible size.

**Before:** 

Screenshot 2023-05-23 at 11 00 09

Screenshot 2023-05-23 at 11 36 59

**After**

Screenshot 2023-05-23 at 10 53 09

Screenshot 2023-05-23 at 11 37 08

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required
other context or links about the pull request here. -->

### Testing instructions

For testing please open up the Icon story and view the new icon with the names listed above.

### CODE REVIEW

**Review by edleeks87 — APPROVED** [review]
Changes LGTM, noticed a few alignment issues as you'd expect with this change to a new font and min font size in some components (eg Pill), I've assumed they'll be fixed in a new ticket and approved

https://www.chromatic.com/test?appId=5ecf782fe724630022d27d7d&id=646cb90dccbabbe60f655b6a

**Review by edleeks87 — DISMISSED** [review]
Changes LGTM, noticed a few alignment issues as you'd expect with this change to a new font and min font size in some components (eg Pill), I've assumed they'll be fixed in a new ticket and approved

https://www.chromatic.com/test?appId=5ecf782fe724630022d27d7d&id=646cb90dccbabbe60f655b6a

**Review by nineteen88 — DISMISSED** [review]

**Comment by harpalsingh** [comment]
Thanks @edleeks87 I have had a review of the pill component and there are several issues that need to be resolved, including the font sizes applied for various sizes, but also padding. So I will address these in a separate PR and we should get these icons in.

**Review by edleeks87 — APPROVED** [review]

**Review by sianford — APPROVED** [review]

**Pull request merged**
