### PR TITLE
Tooltip and shouldComponentUpdate decorator linting

### PR DESCRIPTION
**Pull request by toni-leigh**
## Description

* NB Two tests that were removed were directly calling private functions and therefore don't fit with up to date best practice (they also failed which is why I noticed them)

## QA Notes

* Fire up the demo site and check the Tooltip component

### CODE REVIEW

**Comment by SeanArmstrong** [comment]
Help Component on Chrome which i think has been caused by this tooltip change.

screen shot 2017-06-14 at 14 52 52

**Comment by SeanArmstrong** [comment]
I don't think making any changes to the Help Component would of been a problem. The tooltip decorator is decorating the Help component and therefore they are already tightly coupled. Any change or extra requirement from the tooltip decorator would be a breaking change though

**Comment by SeanArmstrong** [comment]
Tested again on Safari, Chrome, Firefox, Edge, IE11

**Comment by toni-leigh** [comment]
@SeanArmstrong I think also the problem arises in other places, Tooltip is designed to be re-used so it's a bit tricky to expect extra stuff to be done just for this

**Pull request merged**
