### PR TITLE
refactor(multi-select): hide select list on blur

### PR DESCRIPTION
**Pull request by mmaciorowski-sage**
### Proposed behaviour
Hide menu on blur

### Current behaviour
Menu like Select or FilterableSelect stays open when the tab is changed
https://codesandbox.io/s/dazzling-roentgen-snkff?fontsize=14&hidenavigation=1&theme=dark

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context
Fixes: #3833

### Testing instructions
https://codesandbox.io/s/carbon-quickstart-forked-lhcqp?file=/src/index.js

### CODE REVIEW

**Comment by edleeks87** [comment]
Hey @customcodepl I tried reproducing the issue in a sandbox and it doesn't seem to have quite fixed it 

https://codesandbox.io/s/carbon-quickstart-forked-dtjil?file=/src/index.js

**Comment by mmaciorowski-sage** [comment]
> Hey @customcodepl I tried reproducing the issue in a sandbox and it doesn't seem to have quite fixed it
> 
> https://codesandbox.io/s/carbon-quickstart-forked-dtjil?file=/src/index.js

Hi Ed, you are right. It's still in progress. I'll fix it.

**Review by dawidzarzycki — APPROVED** [review]

**Comment by edleeks87** [comment]
@customcodepl can you add it for `SimpleSelect` as well please and tag this issue as fixed when you do

https://codesandbox.io/s/carbon-quickstart-forked-c6u8u?file=/src/index.js:698-710

**Review by edleeks87 — DISMISSED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]
approve for `cypress` tests

**Review by edleeks87 — APPROVED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Pull request merged**
