### PR TITLE
Change unreleased changes document to use carbon-react

### PR DESCRIPTION
**Pull request by SeanArmstrong**
# Description
Since the renaming of the carbon package from opening sourcing the package now must be installed using carbon-react

### CODE REVIEW

**Comment by SeanArmstrong** [comment]
This is then out of sync with the name of the repo

Should we rename the repo on github?

**Comment by toni-leigh** [comment]
@SeanArmstrong ideally yes, not sure about that practically though @chrisbarber86 

A clear *NB* at the top of the docs / readme would be a decent alternative

**Comment by SeanArmstrong** [comment]
At some point that bold text would need to removed?

**Comment by toni-leigh** [comment]
@SeanArmstrong probably, depends how long it takes people's brains to switch over

**Comment by SeanArmstrong** [comment]
Will just ship it for now

**Pull request merged**
