### PR TITLE
WIP - remember config settings

### PR DESCRIPTION
**Pull request by SeanArmstrong**
genurl

# TODO:
Styling
Convert to tinyurl?

### CODE REVIEW

**Comment by toni-leigh** [comment]
This would be really useful

If it existed I would have already used it multiple times

**Comment by toni-leigh** [comment]
UX wise I'd make it auto-populate then the button would copy it to clipboard, rather than having a button to generate

**Comment by SeanArmstrong** [comment]
Discussed in planning to remove encoding for now and just use params?

**Comment by toni-leigh** [comment]
This is a great idea, I hope this closing doesn't mean it's not going to get finished?

**Pull request closed without merging**
