### PR TITLE
docs(rfc): propose internal interfaces

### PR DESCRIPTION
**Pull request by jamime**
Introduce `__internal__` folders to distinguish when components/utilities are for internal use only.

Introduce `@private` and `@ignore` JSDoc annotations to document prop types.

---
This PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/master/rfcs/README.md).

Please use 👍  if you approve.
If you don't approve please comment below.

### CODE REVIEW

**Comment by philearley** [comment]
I take it private items would not be visible on carbon.sage.com ?

**Comment by jamime** [comment]
> I take it private items would not be visible on carbon.sage.com ?

Correct the `__internal__` components wouldn't have dedicated stories. Although we might have some development only stories that aren't published.

The internal props wouldn't be displayed in the prop tables either.

**Comment by jamime** [comment]
This RFC has entered the "Final Comments" stage. This will be accepted unless there are significant changes requested before Thursday 9 July 2020 1330 BST.

**Comment by jamime** [comment]
I've added some minor changes to explain "internal use" and added further detail to the alternative approaches.

**Pull request merged**
