### PR TITLE
refactor(design-tokens): move tokens to global class for usage in pop…

### PR DESCRIPTION
**Pull request by jhajduk-sage**
### Proposed behaviour

Design tokens shall be defined in globally available class. This will make it more reusable, thanks to possibility of applying this class whenever tokens will need to be provided.
Also this class has to be unique for given instance of Carbon because of microfrontends reason.

### Current behaviour

Design tokens are not applied for the elements that are mounted outside `CarbonScopedTokensProvider`.
Currently design tokens are defined only for tokens provider.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

https://codesandbox.io/s/carbon-quickstart-forked-9vpob?file=/src/index.js

### CODE REVIEW

**Comment by mkrds** [comment]
Looks good to me

**Review by mkrds — APPROVED** [review]

**Comment by mkrds** [comment]
I hope you don't mind that I created a commit in your PR to get rid of `sageDesignTokens-undefined` in snapshots :)
Beside that looks good to me

**Comment by jhajduk-sage** [comment]
Of course not! Thanks! :)

**Review by samtjo — APPROVED** [review]

**Review by samtjo — DISMISSED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by samtjo — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Pull request merged**
