### PR TITLE
feat(actionpopoveritem): now supports custom react elements

### PR DESCRIPTION
**Pull request by sagedemdreisbusch**
### Proposed behaviour
Now should render some custom React elements in ActionPopoverItem without throwing console errors
image

### Current behaviour
Throws error when trying to use a react element

### Checklist
- [X] Commits follow our style guide
- [X] Screenshots are included in the PR if useful
- [X] All themes are supported if required
- [X] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [X] Storybook added or updated if required
- [X] Typescript `d.ts` file added or updated if required
- [X] Carbon implementation and Design System documentation are congruent

### Testing instructions
The stry in the storybook is called Action Popover with custom item content

### CODE REVIEW

**Comment by lukeemmerson** [comment]
@dawidzarzycki Do we have a storybook / sandbox example that i can review?

**Comment by jamime** [comment]
This can be achieved with `Popover Container`. I don't think we should merge this. However, we should provide a complete solution for https://github.com/Sage/carbon/issues/3226.

**Comment by maxdreisbusch** [comment]
Hi, if you could provide a workflow for the issue https://github.com/Sage/carbon/issues/3226 that would be great and we would not need his issue :)

**Comment by jamime** [comment]
Great, I'll go ahead and close this. We'll look to implement a complete solution with an example on how to dynamically load items.

Unfortunately I can't provide a date of when we expect this to be completed by.

**Pull request closed without merging**
