### PR TITLE
fix(select-list): fix bottom of focus border is cut off by the select - FE-4022

### PR DESCRIPTION
**Pull request by mmaciorowski-sage**
### Proposed behaviour
Change offset for `popoverModifiers`.

### Current behaviour
When the select input is brought into focus the list covers the bottom part of the focus outline border.
Zrzut ekranu 2021-04-15 o 15 14 04

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Testing instructions
https://codesandbox.io/s/carbon-quickstart-forked-c6fkq

### CODE REVIEW

**Review by DipperTheDan — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Comment by harpalsingh** [comment]
As per the question that was asked, we should fix this 2px gap to be 0px, since different backgrounds can make it look a bit strange, whereas its harder to tell on white backgrounds.

Screenshot 2021-04-22 at 09 18 09

Screenshot 2021-04-22 at 09 18 33

**Comment by mmaciorowski-sage** [comment]
Thank you @harpalsingh. Good point fixed.

**Review by DipperTheDan — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
Tested in Chrome, Edge, Firefox, and Safari. No issue found. Testing Passed.

**Pull request merged**
