### PR TITLE
fix: remove border style from input when disabled

### LINKED ISSUE #4769: [Select - Textbox - Input] - Focus border style sticks on component
### Current behaviour

Given a component that uses an `Input`
When it gets disabled and enabled programmatically 
Then the orange border style is rendered

Here is a [Codesandbox](https://codesandbox.io/s/elated-dawn-6zsbn?file=/src/index.js). Steps to reproduce:
Select the first option
Click the button
The orange border is rendered in both components (`Select` and `Button`) when it should only be in the `Button`.

### Expected behaviour

The orange border only shows up when the element is the active element.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elated-dawn-6zsbn?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

104.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by MarcServat**
fix #4769

### Proposed behaviour

This PR make sure the orange border style from the `Input`, and all components based on it, is rendered when they are focused. 

### Current behaviour

Currently, the input removes its border when it gets disabled but, after enabling it programmatically, the border appears without the `Input` being focused.
image

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

From now on, we will refer to any component that contains a `Input` as `Input`. In a document with several carbon elements, follow the next steps to reproduce:

1. Focus the `Input`
2. Disable the `Input`
3. Press tab, to move the focus to the next element
3. Enable the `Input` programmatically

You'll see both elements (the `Input` and the element focused) have an orange border. See also screenshot above.

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

https://codesandbox.io/s/hidden-night-e406i?file=/src/index.js

### CODE REVIEW

**Comment by samtjo** [comment]
Thanks for the contribution @MarcServat - we're aware of the failing unit test, an issue with our Date component tests that will be resolved soon, we can just rebase this one with master once that's done. 

We'll get this reviewed asap 👍🏻

**Review by samtjo — COMMENTED** [review]
Hi @MarcServat - sorry for the delay, our CI pipeline has been blocked for some time but it's finally up and running again! 

Code changes look ok to me - could you rebase with master please to sort out the failing unit tests then I'll give it a ✅

**Comment by MarcServat** [comment]
Hi @samtjo!
Done :D

**Review by samtjo — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Pull request merged**
