### PR TITLE
fix(card-footer): update the footer non interactive text colour to black

### LINKED ISSUE #2900: card-footer component always shows text in green
### Current behaviour
card-footer renders text in green even though the text is not a hyperlink

image

### Expected behaviour
Normal text is black, hyperlinks are green

### Your environment
Latest react version v17.x

### PR DESCRIPTION
**Pull request by edleeks87**
Fixes #2900

### Proposed behaviour

Only content that is interactive should be green in the card footer

### Current behaviour

All text content in the footer is green

### Checklist

- [x] Release notes (Conventional Commits) 
- [x] Unit tests
<del>- [ ] Cypress automation tests<del>
<del>- [ ] Storybook added or updated<del>
<del>- [ ] Theme support<del>
<del>- [ ] Typescript `d.ts` file added or updated<del>

### Additional context

Proposed Change:
image

Current:
image

### CODE REVIEW

**Comment by ianforster-sage** [comment]
- Are there no circumstances where a footer text would be a Link?
- Are there any tests to be updated to reflect this change?

**Comment by jamime** [comment]
> Are there any tests to be updated to reflect this change?
If there are none, we should add one :)

**Comment by edleeks87** [comment]
> * Are there no circumstances where a footer text would be a Link?
> * Are there any tests to be updated to reflect this change?

The screenshots demonstrate that a Link styling will override the non-interactive content styling.

**Comment by edleeks87** [comment]
> > Are there any tests to be updated to reflect this change?
> 
> If there are none, we should add one 🙂

Have added some snapshot tests

**Pull request merged**
