### PR TITLE
fix(message): reduce left padding of content for `transparent` variant

### LINKED ISSUE #6552: `Message` component `transparent` mode displays extra paddings
### Current behaviour

As shown in this storybook link, 
https://carbon.sage.com/?path=/docs/message--default#transparent
The text in the `Message` component has excessive padding, resulting in a wide gap between the icon and the text itself.

Screenshot 2024-01-30 at 08 42 37

### Expected behaviour

Screenshot 2024-01-30 at 08 45 45

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/message--default#transparent

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

124.6.0

### Design Tokens Version

4.28.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by robinzigmond**
The message conent always has a left padding of 20px. This works fine for most variants with a solid background to the icon, but looks excessively large when the `transparent` variant is used. The padding has therefore been reduced when the `transparent` prop is true.

fix #6552

### Proposed behaviour

There should be less left-padding on the message content for the `transparent` variant, compared to others: 
image

### Current behaviour

There is the same amount of left-padding for the `transparent` variant as for others, which looks excessively large: 
image

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [X] Screenshots are included in the PR if useful
- [X] All themes are supported if required
- [X] Unit tests added or updated if required
- [X] Playwright automation tests added or updated if required
- [X] Storybook added or updated if required
- [X] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [X] Typescript `d.ts` file added or updated if required
- [X] Related docs have been updated if required

#### QA

- [x] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### CODE REVIEW

**Review by tomdavies73 — COMMENTED** [review]
**suggestion** (non-blocking):LGTM, I was just wondering would it be worth adding a unit test for this too? I know we have full coverage here + a snapshot has been updated but a unit test to just catch any breaks down the line could be a good shout.

I'm happy to approve as it is though.

**Comment by nineteen88** [comment]
> > **suggestion** (non-blocking):LGTM, I was just wondering would it be worth adding a unit test for this too? I know we have full coverage here + a snapshot has been updated but a unit test to just catch any breaks down the line could be a good shout.
> > I'm happy to approve as it is though.
> 
> Thanks. Personally I think this is the kind of thing we shouldn't use unit tests for, and Chromatic is perfect for it. But I'll wait to see what a second reviewer says - more than happy to add a unit test for this if it's thought to be needed.

Yeah I don't believe a unit test is required for this personally.

**Comment by nineteen88** [comment]
I thought when we discussed this as a team we were going to just allow a consumer to override the padding themselves for this issue. But as it's been done this way, I'll approve it and @harpalsingh can feedback if it's fine with the variant solution. It is more consistent with how we would typically do it in fairness..

**Review by nineteen88 — APPROVED** [review]

**Review by tomdavies73 — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]

**Pull request merged**
