### PR TITLE
feat(button): make icon only buttons squares - FE-4121

### PR DESCRIPTION
**Pull request by rdzielakpgs**
### Proposed behaviour
**Use case**

Based on feedback from designers, the design system team decided to change the Icon only buttons from rectangle to square.
The page was published in October 2020. Since then, the proposed designs differ from the actual product.

**Acceptance Criteria**

S size icon button is 32px x 32 px
M size icon button is 40px x 40px
L size icon button is 48px x 48px
We refer to Buttons v 0.1.0. This version should be implemented.
Storybook MDX updated with a compatibility table showing which version of the Design System is implemented
The Icon only buttons should be squared, so the padding must be reduced

S-size from 16 to 8px
M-size from 24 to 12px
L-size from 32 to 16px

### Current behaviour
Buttons with icons only are rectangles.

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context
image

### CODE REVIEW

**Review by sjohnson-sage — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by jamime — COMMENTED** [review]
Non blocking.

@rdzielakpgs I see your own acceptance criteria has this
> Storybook MDX updated with a compatibility table showing which version of the Design System is implemented

Are you adding this in a future PR?

**Comment by jamime** [comment]
FE-4297 has been raised to add the table. Merging.

**Review by jamime — CHANGES_REQUESTED** [review]
Waiting for @rdzielakpgs to change the commit type to `feat`.

**Review by DlgSHi — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by sjohnson-sage — APPROVED** [review]

**Review by jamime — APPROVED** [review]

**Review by jamime — APPROVED** [review]

**Pull request merged**
