### PR TITLE
fix(message): add aria label for close button - FE-3335

### PR DESCRIPTION
**Pull request by bulaj**
### Proposed behaviour
VoiceOver describes message close button as "Close button".

### Current behaviour
VoiceOver describes message close button as "button".

### Checklist

- [x] Commits follow our style guide
- [ ] ~~Screenshots are included in the PR if useful~~
- [ ] ~~All themes are supported if required~~
- [ ] ~~Unit tests added or updated if required~~
- [ ] ~~Cypress automation tests added or updated if required~~
- [ ] ~~Storybook added or updated if required~~
- [ ] ~~Typescript `d.ts` file added or updated if required~~
- [ ] ~~Carbon implementation and Design System documentation are congruent~~

### Additional context
Added aria-label as suggested.
Exposed prop "closeButtonAriaLabel" allowing to customise this label.
Added support for i18n.

### Testing instructions
Turn on voice over in system preferences > accessibility.
Proceed to message example on storybook then tab-focus to the button.

### CODE REVIEW

**Comment by edleeks87** [comment]
I think this should just be a `fix` commit @bulaj

**Review by edleeks87 — COMMENTED** [review]
I think this should just be a fix commit @bulaj

**Comment by DipperTheDan** [comment]
Good day. Could you also add `fixes #3406` to your commit message please? This will ensure that issue https://github.com/Sage/carbon/issues/3406 is closed when you merge the PR. Thanks 👍🏻

**Comment by DipperTheDan** [comment]
> I think this should just be a fix commit @bulaj

In addition to this, could you also add fixes #3406 to your commit message please? This will ensure that issue #3406 is closed when you merge the PR. Thanks 👍🏻

**Review by edleeks87 — DISMISSED** [review]

**Review by jamime — CHANGES_REQUESTED** [review]
We need to support i18n anywhere that we use an english string, but it should be overridable by using a prop.

```js
aria-label={ariaLabel || I18n.t("message.aria-label", {
  defaultValue: "close",
})}
```

We're going to review our i18n strategy this year, the proposal is here
https://github.com/Sage/carbon/blob/master/rfcs/text/i18n.md

Icon button is already a `button`, the aria label `close button` would read out `close button, button`, I think we should default to `close`.

https://github.com/Sage/carbon/blob/35c5161306eae706a1bf9bb50bdcd92632f1edb9/src/components/icon-button/icon-button.style.js#L5

**Comment by jamime** [comment]
> > I think this should just be a fix commit @bulaj
> 
> In addition to this, could you also add `fixes #3406` to your commit message please? This will ensure that issue #3406 is closed when you merge the PR. Thanks 👍🏻

In regards to the commit message the commit has to have a `footer` for `semantic-release` to pick it up correctly.

```
fix(message): add aria label to close button 

Fixes #3406
```

There are more details here: https://github.com/Sage/carbon/blob/master/CONTRIBUTING.md#git-commit-messages

**Comment by bulaj** [comment]
> Icon button is already a `button`, the aria label `close button` would read out `close button, button`, I think we should default to `close`.
@jamime It looks like there is a discrepancy between how voice readers announce the elements. VoiceOver on mac OS says "Close button", while on Windows "Close button, button" as you predicted.
How should we approach this issue.

**Comment by jamime** [comment]
> > Icon button is already a `button`, the aria label `close button` would read out `close button, button`, I think we should default to `close`.
> 
> @jamime It looks like there is a discrepancy between how voice readers announce the elements. VoiceOver on mac OS says "Close button", while on Windows "Close button, button" as you predicted.
> 
> How should we approach this issue?

I actually tested it using VoiceOver for MacOS and it read "Close button, button".


https://user-images.githubusercontent.com/2328042/105825131-2804f700-5fb7-11eb-8357-a6170eac998a.mov

I'm not sure why the focus jumps from the message text to the close button, but it's unrelated to this ticket.

**Comment by bulaj** [comment]
@jamime turns out it is dependant on voiceover verbosity and its configurable. I had verbosity set to "lower". Default is "medium", which gives the "button, button" description. I'm going to change that.

**Review by jamime — APPROVED** [review]

**Review by jamime — CHANGES_REQUESTED** [review]
Please can you add a unit test, everything else looks fine 👍

**Comment by bulaj** [comment]
> Please can you add a unit test, everything else looks fine 👍

@jamime Thanks, added.

**Review by edleeks87 — APPROVED** [review]

**Review by jamime — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Pull request merged**
