### PR TITLE
feat(sidebar, drawer and dialogs): adjust background of modal headers to be white instead of grey

### PR DESCRIPTION
**Pull request by ljemmo**
addresses #5394

### Proposed behaviour

Dialog, Full screen dialog and Sidebar headers are now white in order to mirror the [Design System Spec](https://www.figma.com/file/Tau6qv5iyr8wthWNqYktej/DS-Official-Components?node-id=706%3A41976).

Screenshot 2022-09-29 at 17 23 34
Screenshot 2022-09-29 at 17 20 59

### Current behaviour

Dialog, Full screen dialog and Sidebar headers were gray.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by DobroTora — DISMISSED** [review]
LGTM :)

**Review by DipperTheDan — COMMENTED** [review]
Code changes look OK. The commits need tidying up a bit so would you be able to do that please? It should just be one commit of `feat(sidebar, drawer and dialogs): adjust...`

**Comment by ljemmo** [comment]
@DipperTheDan  this has now been actioned

**Review by edleeks87 — DISMISSED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Comment by harpalsingh** [comment]
@ljemmo white I understand the reason for this on dialog, this could be a problem on Drawer and so we should hold merging or progressing with this PR until that has been discussed please.

**Comment by ljemmo** [comment]
@harpalsingh i've now removed the white header as discussed for the drawer.

**Comment by ljemmo** [comment]
@edleeks87  or @Parsium  - please can i get another review. Aparrently it needs your thumbs up before QA can pick it up.

**Review by DipperTheDan — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]

**Pull request merged**
