### PR TITLE
feat(switch): change hover behaviour

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour
Screenshot 2021-06-28 at 09 12 34

The component will no longer have outline on hover, it will change it's background color mirroring the Button Component

### Current behaviour
Screenshot 2021-06-23 at 15 45 46

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
~~- [ ] Cypress automation tests added or updated if required~~
~~- [ ] Storybook added or updated if required~~
~~- [ ] Typescript `d.ts` file added or updated if required~~
~~- [ ] Carbon implementation and Design System documentation are congruent~~

### CODE REVIEW

**Comment by dawidzarzycki** [comment]
I think that design provided by this PR is incorrect 
Attached screenshot shows hover state on gray switch (off)
image
I guess the color on hover should be darker than gray , not green one.

**Review by dawidzarzycki — CHANGES_REQUESTED** [review]
I think that design provided by this PR is incorrect 
Attached screenshot shows hover state on gray switch (off)
image
I guess the color on hover should be darker than gray , not green one.

**Review by DipperTheDan — APPROVED** [review]

**Review by dawidzarzycki — APPROVED** [review]
@grabkowski Please, update the image attached to the PR with the fixed one

**Review by DlgSHi — APPROVED** [review]

**Pull request merged**
