### PR TITLE
refactor(button): add missing props to propTypes

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour
Add event props and the type prop to Button propTypes to allow type checking of these props

### Checklist

- [x] Commits follow our style guide
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
~~- [ ] Unit tests added or updated if required~~
~~- [ ] Cypress automation tests added or updated if required~~
~~- [ ] Storybook added or updated if required~~
- [x] Typescript `d.ts` file added or updated if required
~~- [ ] Carbon implementation and Design System documentation are congruent~~

### CODE REVIEW

**Review by nicktitchmarsh — APPROVED** [review]

**Review by ianforster-sage — COMMENTED** [review]
Github Actions has 5 lint warning for missing prop validations in `src/components/button/button.components.js`. Are you sure we don't need them?

**Comment by grabkowski** [comment]
> Github Actions has 5 lint warning for missing prop validations in `src/components/button/button.components.js`. Are you sure we don't need them?

All these props could be found in propTypes, these warnings are related to the button's children that are rendered in a separate method.

**Comment by ianforster-sage** [comment]
> > Github Actions has 5 lint warning for missing prop validations in `src/components/button/button.components.js`. Are you sure we don't need them?
> 
> All these props could be found in propTypes, these warnings are related to the button's children that are rendered in a separate method.

OK. ✅  approved

**Review by ianforster-sage — APPROVED** [review]

**Pull request merged**
