### PR TITLE
Make confirm button contents more flexible

### PR DESCRIPTION
**Pull request by toni-leigh**
* Quick fix to make the Confirm button more flexible

### CODE REVIEW

**Comment by ianoxley** [comment]
I'm not sure what the use case is here. Can you give an example of where this would be useful please?

**Comment by toni-leigh** [comment]
@ianoxley I needed to put an icon into a confirm button

**Comment by andrewjtait** [comment]
Release notes need updating to match new format.

**Comment by toni-leigh** [comment]
@andrewjtait addressed

**Comment by andrewjtait** [comment]
Currently being refactored so will close.

**Pull request closed without merging**
