### PR TITLE
Add a prop to enable/disable the setting of the selected tabId in the…

### LINKED ISSUE #1887: Changing tab changes the URL
**Issue:**

When a tab is selected, the URL is changed by this code: https://github.com/Sage/carbon/blob/d872f938a67258669013bacdd8df954e0089e525/src/components/tabs/tabs.js#L337 
https://github.com/Sage/carbon/blob/d872f938a67258669013bacdd8df954e0089e525/src/components/tabs/tabs.js#L338

**Use case:**

This presents an issue when a react application returns "Fragments" from the render method of a component, which is something that you may wish to do in the absence of a routing engine, i.e. when serving the site out of S3, as a URL can only contain one '#' element.  

**Suggestion:**

Make this functionality optional.

### LINKED ISSUE #2054: Tab className not used
I want to change the color of one of my tabs.
if i add a className to the Tab component, that className is ignored.
A li and a div are generated for each Tab but neither of them has the className.

I would like to have the className at least on the li

### PR DESCRIPTION
**Pull request by gusch**
# Description
Add a `setLocation` prop (true by default). If true, the selected tabId will be added to the URL
fixes #1887
fixes #2054

### CODE REVIEW

**Comment by gusch** [comment]
.

**Comment by gusch** [comment]
@edleeks87 I targeted the release branch and added a new yml file in change_log/next. I also updated the description of the PR. Is it ok for you ?

**Comment by gusch** [comment]
I see the tests are failling. How do i run them locally ? Is it possible to only run the tests for the tab component ?

**Comment by gusch** [comment]
Also, continuous-integration/codeship build failed but i have not access to it.

**Comment by edleeks87** [comment]
Oh sorry I didn't realise you had no access, I will see if I can sort that for you. In the meantime, the build is failing as the tests are now broken, you will need to fix them to get a passing build, it can't be merged until everything passes. If you run `npm run test` you will see which tests are now broken in carbon and need fixing

**Comment by edleeks87** [comment]
Looking at the build you can just run `npm run test src/components/tabs/__spec__.js -- --watch` to target the specific suite as that is the only one that is failing

**Comment by edleeks87** [comment]
@sianford are you okay to QA this PR please?

**Comment by sianford** [comment]
@edleeks87 no problem, I'll pick this up.

**Comment by sianford** [comment]
@gusch this prop seems to behave as expected with setting the tab location. However, in the description it states "Add a setLocation prop (true by default)" but this prop is not set by default. Can you please confirm if it is meant to be set by default?

**Comment by gusch** [comment]
@sianford My bad. I forgot to add the default value. It's now done.

**Comment by sianford** [comment]
Retested this with the default value set to 'true'. This appears to be working as expected now. Testing passed.

**Pull request merged**
