### PR TITLE
feat(draggable): adds dragged item id to getColumns callback of draggable component

### PR DESCRIPTION
**Pull request by blaky**
### Proposed behaviour

On the top of the new order of items, the arguments of `getColumns()` callback should also contain the `id` of the element that was just dropped.

### Current behaviour

The arguments of the getColumns() callback only contains the new order of items. It is not ideal because if the list of items is filtered, it is very difficult to work out which item was moved. 

### Checklist

- [X] Commits follow our style guide
- [ N/A ] Related issues linked in commit messages if required
- [ N/A ] Screenshots are included in the PR if useful
- [ N/A ] All themes are supported if required
- [X] Unit tests added or updated if required
- [N/A] Cypress automation tests added or updated if required
- [N/A] Storybook added or updated if required
- [N/A] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [X] Typescript `d.ts` file added or updated if required
- [N/A] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

I fixed a typing issue, the id of the draggable element can be `string` or `number` but the `getColumns()` argument was always a number[], but on runtime it can return a number or a string array.

### Testing instructions

Here is a sandbox: https://codesandbox.io/s/carbon-quickstart-forked-9vyhnc?file=/src/index.js

### CODE REVIEW

**Comment by blaky** [comment]
Hi @edleeks87 ,

Could you please review this PR? It blocks us from going ahead with a feature we need. The only thing this change does is to pass on an argument coming from `react-dnd` to the consuming product.

Thanks

**Review by Parsium — COMMENTED** [review]
Likewise looks good to me @blaky 👍🏼 Happy to accept once @DipperTheDan's comment has been addressed :)

**Comment by blaky** [comment]
> Code looks fine @blaky Just one minor thing please. Could you amend the commit message to be `feat(draggable): adds dragged item id to getColumns callback of draggable component`. It just ensures our release notes will be formatted correctly when this gets merged. Thanks! 😃

Updated!

**Review by Parsium — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Pull request merged**
