### PR TITLE
DLS Tooltip - duplicate of PR #2118

### PR DESCRIPTION
**Pull request by stevebutler2210**
Identical to closed PR https://github.com/Sage/carbon/pull/2118, which was merged early in error before UX review had been conducted (reverted here https://github.com/Sage/carbon/pull/2154).

### CODE REVIEW

**Comment by harpalsingh** [comment]
When using the "warning" style, we still see it as a dark tooltip?

What we see:
Screenshot 2019-06-26 at 11 03 58

Could the font weight be reverted to use 700 for all designs, same as classic so we see the bold weight:

currently:
Screenshot 2019-06-26 at 11 04 47

What we would like:
Screenshot 2019-06-26 at 11 04 44

In the design here http://designsystem.sage.com/patterns/help-tooltips/ the tooltips have a short fade in animation, does this apply to the tooltips? Triggering isVisible does not seem to show if this does that.

Could the padding please be updated to be 8px for top/bottom and 16px for left and right.

**Comment by stevebutler2210** [comment]
Thanks for your feedback @harpalsingh 

> When using the "warning" style, we still see it as a dark tooltip?

This is as per the designs here:
http://designsystem.sage.com/components/text-inputs/

> Could the font weight be reverted to use 700 for all designs, same as classic so we see the bold weight

Can do - as this is a deviation from the current designs, will these be updated to reflect the change?

>In the design here http://designsystem.sage.com/patterns/help-tooltips/ the tooltips have a short fade in animation, does this apply to the tooltips? Triggering isVisible does not seem to show if this does that.

Yep, totally missed this - guessing this should be applied at all times for all tooltips using one of the new themes?

> Could the padding please be updated to be 8px for top/bottom and 16px for left and right.

Another good catch, will update, sorry!

**Comment by harpalsingh** [comment]
Thanks @stevebutler2210 

I'll confirm on the warning, but for the rest, once we see it in a build, it helps to determine if there are any tweaks on the original design and where changes are suggested here, they will then be updated on the design system portal in short time, if they vary.

**Comment by harpalsingh** [comment]
ok with leaving warning as it is 👍

**Pull request merged**
