### PR TITLE
fix hover dropdown and action popover hover colours so they align with figma implementation

### PR DESCRIPTION
**Pull request by ljemmo**
### Proposed behaviour

- Change dropdown menu item hover colour and action popover menu item hover to use a light gray as opposed to dark. new colour token = 'colorsUtilityMajor100'
- Removed styling overrides for dropdown menu sticky footer button to align with figma implementation. 
Screenshot 2022-08-30 at 16 32 05

### Current behaviour
old colour tokenused  = 'colorsUtilityMajor200'
Screenshot 2022-08-30 at 15 16 22

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by edleeks87 — CHANGES_REQUESTED** [review]
Hey @ljemmo some snapshot tests are now failing so you'll need to update them by running `npm test -- -u` and amend the commit to include the updates. When you're doing that the commit message should be something like `chore: (action-popover, option, option-row): update background hover colour to match latest figma designs`

**Comment by mkrds** [comment]
Pretty much what Ed said, I'll happily approve it after you'll do te requested changes

**Review by edleeks87 — APPROVED** [review]

**Review by mkrds — APPROVED** [review]

**Review by sianford — APPROVED** [review]
Tested in Safari, Chrome, Firefox and Edge. Token colour has been updated correctly. New tests added for hover state in Action Popover and Select. Testing passed ✅

**Review by DipperTheDan — APPROVED** [review]

**Review by edleeks87 — COMMENTED** [review]
I'm going to merge this, @sianford please can you raise a new PR to remove the duplicate test in `src/components/action-popover/action-popover.test.js`

**Pull request merged**
