### PR TITLE
fix(multi-action-button): change button text position (FE-2081)

### PR DESCRIPTION
**Pull request by grabkowski**
Dropdown icon was removed from the multi action button.
Rendering of the Icon moved directly into the button to keep consistency with other buttons.

### Proposed behaviour
Render the main button in Multi Action Button by passing the "iconType" prop to the Button Component to avoid style inconsistencies and needless style overrides.

### Current behaviour
Multi Action main button icon is rendered as a child of the button.

### Checklist
- [x] Release notes (Conventional Commits) 
- [x] Unit tests
~~- [ ] Cypress automation tests~~
~~- [ ] Storybook added or updated~~
- [x] Theme support
~~- [ ] Typescript `d.ts` file added or updated~~

### CODE REVIEW

**Comment by jamime** [comment]
@grabkowski is this a breaking change for our users, what will they have to do differently?

**Comment by grabkowski** [comment]
> @grabkowski is this a breaking change for our users, what will they have to do differently?

I think that I may have misunderstood what should be a `BREAKING CHANGE`. I'll amend that commit message.

**Comment by sianford** [comment]
Tested in Safari, Chrome, Firefox, Edge and IE11 browsers. The buttons and text within in all default and classic stories are aligned in all browsers. Testing passed ✅

**Pull request merged**
