### PR TITLE
fix(colors): make used colors in Carbon DLS compliant

### PR DESCRIPTION
**Pull request by arturodrigues**
### Proposed behaviour
Colors should be compliant with DLS specifications.

### Current behaviour
There is a mismatch between Carbon and DLS colors. Example:

- DLS

image

- Carbon:
image

### Checklist

- [x] Release notes (Conventional Commits) 
- [x] Unit tests
- [x] Cypress automation tests
- <del> Storybook added or updated</del>
- [x] Theme support
- <del>Typescript `d.ts` file added or updated</del>

### Additional context
This fixes issue #2889 

### Testing instructions

Confirm that all colors now follow DLS specs. Executing UT's and Cypress e2e tests and check that they pass.

### CODE REVIEW

**Comment by jamime** [comment]
Thanks for raising this @arturodrigues,

We need to be wary of components that consist of both `Sass` and `styled-components`, or even designs that use both components.

We've historically accepted that the `Sass` utility generates a slightly different color compared to `Sketch`, this was then copied into `styled-components` so we have one consistent, but slightly different color palette.

As it stands this PR could result in two different colours.

e.g. This `Sass` comment was updated, but it still results in the color `#F2F4F5`.

```diff
- $slate-tint-95:          mix(white, $slate, 95) !default; // #F2F4F5
+ $slate-tint-95:          mix(white, $slate, 95) !default; // #F2F5F6
```

You can see this example here: https://www.sassmeister.com/gist/76eb0d1c2ce799fba1b8f3ce12f7f6de



It's great that we can match it with `styled-components` but the `Sass` values would still be wrong. I think the only way to make these implementations match is to update this

https://github.com/Sage/carbon/pull/2890/files#diff-d9f5fb0774574d25f6e938af7e711d33
to use a custom `Sass` function, or use HEX codes.

**Comment by arturodrigues** [comment]
Hello @jamime,

Thank you for your answer. While I was reading your comment, I was wondering why the UT's weren't failing if mix method from SASS doesn't return the correct value. Then, I checked your screenshot and I saw the returned value is actually the one that DLS has. This way, I tested for various shades of slate, and all of them are correct:

image

Please compare with the image from DLS I copied in the PR comment above.

Hence, I think now we have colors from SASS and styled-components matching and this is not an issue.

Please confirm.

Best regards,
Arturo

**Comment by jamime** [comment]
🤦 my mistake. I've realised it's even in the screenshot I sent.
I must have assumed that the existing comments in `Sass` were accurate.

Great work 👏 

@dawidzarzycki is the assignee so he'll take it from here.

**Comment by harpalsingh** [comment]
I'll scan through this, but just an important point to note, we treat our base colors with any combination of white or black against them.

you can see various values here:
https://designsystem.sage.com/foundations/colour-generator/

So while fixed HEX values can be udpated, is there no way to avoid a hex value and use a calculation like SASS does instead? @jamime @arturodrigues

**Comment by arturodrigues** [comment]
Hello @harpalsingh , not sure if I follow you.

In this PR, I changed .\src\style\utils\mix.js to have a correct calculation of hex values, like SASS and DLS do.

Thanks,
Arturo

**Comment by dawidzarzycki** [comment]
Hello @arturodrigues 

The code looks good to me.
There are two things that would be good to do before it will go forward
- resolving conflicts
- squashing commits into one

**Comment by harpalsingh** [comment]
@arturodrigues Ok thanks ,all good, I mis-took the spec file!

**Comment by arturodrigues** [comment]
Hello @dawidzarzycki ,

I have squashed my commits and pushed it. Can you please proceed?

Thanks,
Arturo

**Comment by dawidzarzycki** [comment]
@arturodrigues 
Did you push your changes? I still can see conflict and 11 commits.
Remember that after squash you will need to push the code with `force` flag

**Comment by arturodrigues** [comment]
Hello @dawidzarzycki ,

The conflict was a new one from today. Nevertheless, I didn't push it with -f flag. Now I have solved this new conflict, squashed it again and pushed it correctly.

Please proceed.

Regards,
Arturo

**Comment by dawidzarzycki** [comment]
@arturodrigues Hey!
Thanks for the changes, just one more thing. We have already 1 commit but still it is combined with rest commits. 
```
fix(colors): make used colors in Carbon DLS compliant
fix(colors): fix mix method to comply with DLS tint and shade colors
fix(colors): fix colors to comply with DLS
test(colors): updated test and snapshots after color changes
test(cypress): updated step and feature files after color changes
docs(colors): adapt documentation example with new color
test(action-popover): updated snapshot
test(flat-table): updated snapshot
```
I think that we could just stay with this one
```
fix(colors): make used colors in Carbon DLS compliant
```

Thank you in advance! :)

**Comment by arturodrigues** [comment]
@dawidzarzycki , done!

**Comment by arturodrigues** [comment]
Let's hope this time is for good, @dawidzarzycki !

**Comment by DlgSHi** [comment]
Hi, I've run our regression suite and there are few colours missed to update:

**`FlatTable sortable component`**
_Flat table header has dark color_
Timed out retrying: expected '<th.sc-eKZiaR.gkGoRM>' to have CSS property 'background-color' with the value 'rgb(51, 91, 109)', but the value was 'rgb(51, 9**2**, 109)'

_Flat table header has light color_
Timed out retrying: expected '<th.sc-eKZiaR.gkGoRM>' to have CSS property 'background-color' with the value 'rgb(204, 214, 218)', but the value was 'rgb(204, 214, 21**9**)'

_Flat table header has transparent-base color_
Timed out retrying: expected '<th.sc-eKZiaR.gkGoRM>' to have CSS property 'background-color' with the value 'rgb(242, 244, 245)', but the value was 'rgb(242, 24**5**, 24**6**)'

**`Pill component`**
_Verify the colorVariant color for status pillRole_
Timed out retrying: expected '<span.sc-kjoXOD.jHpNyA>' to have CSS property 'border-bottom-color' with the value 'rgb(76, 112, 127)', but the value was 'rgb(7**7**, 112, 12**8**)'

**`Show Edit Pod component`**
_Change Pod type to tertiary_
Timed out retrying: expected '<div.sc-iybRtq.jFywMG>' to have CSS property 'background-color' with the value 'rgb(229, 234, 236)', but the value was 'rgb(2**30**, 23**5**, 23**7**)'

_Enable saving checkbox for a Show Edit Pod component_
Timed out retrying: expected '<button.sc-cSHVUG.eULUZq>' to have CSS property 'background' with the value 'rgb(229, 234, 236) none repeat scroll 0% 0% / auto padding-box border-box', but the value was 'rgb(2**30**, 23**5**, 23**7**) none repeat scroll 0% 0% / auto padding-box border-box'

_Set Show Edit Pod podType property to tertiary_
Timed out retrying: expected '<div.sc-iybRtq.DfEwH>' to have CSS property 'background-color' with the value 'rgb(229, 234, 236)', but the value was 'rgb(2**30**, 23**5**, 23**7**)'

**`Split Button component`**
_Verify hover color and golden border for first element of Split Button component_
Timed out retrying: expected '<button.sc-cSHVUG.kiiYld>' to have CSS property 'background-color' with the value 'rgb(0, 63, 46)', but the value was 'rgb(0, 6**4**, 46)'

_Verify hover color and golden border for second element of Split Button component_
Timed out retrying: expected '<button.sc-cSHVUG.kiiYld>' to have CSS property 'background-color' with the value 'rgb(0, 63, 46)', but the value was 'rgb(0, 6**4**, 46)'

_Verify hover color and golden border for third element of Split Button component_
Timed out retrying: expected '<button.sc-cSHVUG.kiiYld>' to have CSS property 'background-color' with the value 'rgb(0, 63, 46)', but the value was 'rgb(0, 6**4**, 46)’

**`Table component`**
_I enable zebra striping for 0 row in Table_ (notice for all steps)
Timed out retrying: expected '<td.sc-kPVwWT.fmPFbz>' to have CSS property 'background-color' with the value 'rgb(249, 250, 251)', but the value was 'rgb(2**50**, 251, 251)'

_Set theme to primary_
Timed out retrying: expected '[ <th.sc-hwwEjo.bcgtTB>, 1 more... ]' to have CSS property 'background-color' with the value 'rgb(51, 91, 109)', but the value was 'rgb(51, 9**2**, 109)'

**`Table With Inputs component`**
_I enable zebra striping for 0 row in Table_ (notice for all steps)
Timed out retrying: expected '<td.sc-kPVwWT.iZHwij>' to have CSS property 'background-color' with the value 'rgb(249, 250, 251)', but the value was 'rgb(2**50**, 251, 251)'

_Set theme to primary_
Timed out retrying: expected '[ <th.sc-hwwEjo.bcgtTB>, 1 more... ]' to have CSS property 'background-color' with the value 'rgb(51, 91, 109)', but the value was 'rgb(51, 9**2**, 109)'

**Comment by arturodrigues** [comment]
Hello @DlgSHi ,

I have pushed the requested changes in order to fix the cypress tests. May you try again, please?

**Comment by dawidzarzycki** [comment]
Hi @arturodrigues ,

I can see that QA looks good now. After resolving conflicts I'll be happy to approve all the changes

**Comment by arturodrigues** [comment]
Hello @dawidzarzycki ,

Pushed the changes after solving the conflicts. Let's hope build succeeds and then let's carry on with the approval.

Thank you,
Arturo

**Pull request merged**
